name: An Nguyen Van Chuc
description: About An Nguyen Van Chuc
url: https://annguyenwasd.github.io
baseurl: ""
author: An Nguyen Van Chuc
timezone: Asia/Ho_Chi_Minh
timezone_short: ICT
lang: en

keywords:
  - An Nguyen Van Chuc
  - software developer
  - front-end development
  - web development

analytics:
  plausible:
    enabled: false
    site_fqdn: annguyenwasd.github.io
    script_source: https://plausible.io/js/script.js

sass:
  sass_dir: _sass
  style: expanded

exclude:
  - README.md
  - COPYING
  - Gemfile
  - Gemfile.lock
  - vendor

plugins:
  - jekyll-seo-tag
